// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// StreamRequestColumns holds the columns for the "stream_request" table.
	StreamRequestColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "request_id", Type: field.TypeInt},
		{Name: "request_type", Type: field.TypeString},
		{Name: "is_active", Type: field.TypeBool},
	}
	// StreamRequestTable holds the schema information for the "stream_request" table.
	StreamRequestTable = &schema.Table{
		Name:       "stream_request",
		Columns:    StreamRequestColumns,
		PrimaryKey: []*schema.Column{StreamRequestColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		StreamRequestTable,
	}
)

func init() {
	StreamRequestTable.Annotation = &entsql.Annotation{
		Table: "stream_request",
	}
}
