// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/skkugoon/strattonight/ent/predicate"
	"github.com/skkugoon/strattonight/ent/streamrequest"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeStreamRequest = "StreamRequest"
)

// StreamRequestMutation represents an operation that mutates the StreamRequest nodes in the graph.
type StreamRequestMutation struct {
	config
	op            Op
	typ           string
	id            *int
	request_id    *int
	addrequest_id *int
	request_type  *string
	is_active     *bool
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*StreamRequest, error)
	predicates    []predicate.StreamRequest
}

var _ ent.Mutation = (*StreamRequestMutation)(nil)

// streamrequestOption allows management of the mutation configuration using functional options.
type streamrequestOption func(*StreamRequestMutation)

// newStreamRequestMutation creates new mutation for the StreamRequest entity.
func newStreamRequestMutation(c config, op Op, opts ...streamrequestOption) *StreamRequestMutation {
	m := &StreamRequestMutation{
		config:        c,
		op:            op,
		typ:           TypeStreamRequest,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withStreamRequestID sets the ID field of the mutation.
func withStreamRequestID(id int) streamrequestOption {
	return func(m *StreamRequestMutation) {
		var (
			err   error
			once  sync.Once
			value *StreamRequest
		)
		m.oldValue = func(ctx context.Context) (*StreamRequest, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().StreamRequest.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withStreamRequest sets the old StreamRequest of the mutation.
func withStreamRequest(node *StreamRequest) streamrequestOption {
	return func(m *StreamRequestMutation) {
		m.oldValue = func(context.Context) (*StreamRequest, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m StreamRequestMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m StreamRequestMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of StreamRequest entities.
func (m *StreamRequestMutation) SetID(id int) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *StreamRequestMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *StreamRequestMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().StreamRequest.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetRequestID sets the "request_id" field.
func (m *StreamRequestMutation) SetRequestID(i int) {
	m.request_id = &i
	m.addrequest_id = nil
}

// RequestID returns the value of the "request_id" field in the mutation.
func (m *StreamRequestMutation) RequestID() (r int, exists bool) {
	v := m.request_id
	if v == nil {
		return
	}
	return *v, true
}

// OldRequestID returns the old "request_id" field's value of the StreamRequest entity.
// If the StreamRequest object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *StreamRequestMutation) OldRequestID(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldRequestID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldRequestID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldRequestID: %w", err)
	}
	return oldValue.RequestID, nil
}

// AddRequestID adds i to the "request_id" field.
func (m *StreamRequestMutation) AddRequestID(i int) {
	if m.addrequest_id != nil {
		*m.addrequest_id += i
	} else {
		m.addrequest_id = &i
	}
}

// AddedRequestID returns the value that was added to the "request_id" field in this mutation.
func (m *StreamRequestMutation) AddedRequestID() (r int, exists bool) {
	v := m.addrequest_id
	if v == nil {
		return
	}
	return *v, true
}

// ResetRequestID resets all changes to the "request_id" field.
func (m *StreamRequestMutation) ResetRequestID() {
	m.request_id = nil
	m.addrequest_id = nil
}

// SetRequestType sets the "request_type" field.
func (m *StreamRequestMutation) SetRequestType(s string) {
	m.request_type = &s
}

// RequestType returns the value of the "request_type" field in the mutation.
func (m *StreamRequestMutation) RequestType() (r string, exists bool) {
	v := m.request_type
	if v == nil {
		return
	}
	return *v, true
}

// OldRequestType returns the old "request_type" field's value of the StreamRequest entity.
// If the StreamRequest object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *StreamRequestMutation) OldRequestType(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldRequestType is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldRequestType requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldRequestType: %w", err)
	}
	return oldValue.RequestType, nil
}

// ResetRequestType resets all changes to the "request_type" field.
func (m *StreamRequestMutation) ResetRequestType() {
	m.request_type = nil
}

// SetIsActive sets the "is_active" field.
func (m *StreamRequestMutation) SetIsActive(b bool) {
	m.is_active = &b
}

// IsActive returns the value of the "is_active" field in the mutation.
func (m *StreamRequestMutation) IsActive() (r bool, exists bool) {
	v := m.is_active
	if v == nil {
		return
	}
	return *v, true
}

// OldIsActive returns the old "is_active" field's value of the StreamRequest entity.
// If the StreamRequest object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *StreamRequestMutation) OldIsActive(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldIsActive is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldIsActive requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldIsActive: %w", err)
	}
	return oldValue.IsActive, nil
}

// ResetIsActive resets all changes to the "is_active" field.
func (m *StreamRequestMutation) ResetIsActive() {
	m.is_active = nil
}

// Where appends a list predicates to the StreamRequestMutation builder.
func (m *StreamRequestMutation) Where(ps ...predicate.StreamRequest) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the StreamRequestMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *StreamRequestMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.StreamRequest, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *StreamRequestMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *StreamRequestMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (StreamRequest).
func (m *StreamRequestMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *StreamRequestMutation) Fields() []string {
	fields := make([]string, 0, 3)
	if m.request_id != nil {
		fields = append(fields, streamrequest.FieldRequestID)
	}
	if m.request_type != nil {
		fields = append(fields, streamrequest.FieldRequestType)
	}
	if m.is_active != nil {
		fields = append(fields, streamrequest.FieldIsActive)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *StreamRequestMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case streamrequest.FieldRequestID:
		return m.RequestID()
	case streamrequest.FieldRequestType:
		return m.RequestType()
	case streamrequest.FieldIsActive:
		return m.IsActive()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *StreamRequestMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case streamrequest.FieldRequestID:
		return m.OldRequestID(ctx)
	case streamrequest.FieldRequestType:
		return m.OldRequestType(ctx)
	case streamrequest.FieldIsActive:
		return m.OldIsActive(ctx)
	}
	return nil, fmt.Errorf("unknown StreamRequest field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *StreamRequestMutation) SetField(name string, value ent.Value) error {
	switch name {
	case streamrequest.FieldRequestID:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetRequestID(v)
		return nil
	case streamrequest.FieldRequestType:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetRequestType(v)
		return nil
	case streamrequest.FieldIsActive:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetIsActive(v)
		return nil
	}
	return fmt.Errorf("unknown StreamRequest field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *StreamRequestMutation) AddedFields() []string {
	var fields []string
	if m.addrequest_id != nil {
		fields = append(fields, streamrequest.FieldRequestID)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *StreamRequestMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case streamrequest.FieldRequestID:
		return m.AddedRequestID()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *StreamRequestMutation) AddField(name string, value ent.Value) error {
	switch name {
	case streamrequest.FieldRequestID:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddRequestID(v)
		return nil
	}
	return fmt.Errorf("unknown StreamRequest numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *StreamRequestMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *StreamRequestMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *StreamRequestMutation) ClearField(name string) error {
	return fmt.Errorf("unknown StreamRequest nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *StreamRequestMutation) ResetField(name string) error {
	switch name {
	case streamrequest.FieldRequestID:
		m.ResetRequestID()
		return nil
	case streamrequest.FieldRequestType:
		m.ResetRequestType()
		return nil
	case streamrequest.FieldIsActive:
		m.ResetIsActive()
		return nil
	}
	return fmt.Errorf("unknown StreamRequest field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *StreamRequestMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *StreamRequestMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *StreamRequestMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *StreamRequestMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *StreamRequestMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *StreamRequestMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *StreamRequestMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown StreamRequest unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *StreamRequestMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown StreamRequest edge %s", name)
}
