// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/skkugoon/strattonight/ent/predicate"
	"github.com/skkugoon/strattonight/ent/streamrequest"
)

// StreamRequestDelete is the builder for deleting a StreamRequest entity.
type StreamRequestDelete struct {
	config
	hooks    []Hook
	mutation *StreamRequestMutation
}

// Where appends a list predicates to the StreamRequestDelete builder.
func (srd *StreamRequestDelete) Where(ps ...predicate.StreamRequest) *StreamRequestDelete {
	srd.mutation.Where(ps...)
	return srd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (srd *StreamRequestDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, srd.sqlExec, srd.mutation, srd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (srd *StreamRequestDelete) ExecX(ctx context.Context) int {
	n, err := srd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (srd *StreamRequestDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(streamrequest.Table, sqlgraph.NewFieldSpec(streamrequest.FieldID, field.TypeInt))
	if ps := srd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, srd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	srd.mutation.done = true
	return affected, err
}

// StreamRequestDeleteOne is the builder for deleting a single StreamRequest entity.
type StreamRequestDeleteOne struct {
	srd *StreamRequestDelete
}

// Where appends a list predicates to the StreamRequestDelete builder.
func (srdo *StreamRequestDeleteOne) Where(ps ...predicate.StreamRequest) *StreamRequestDeleteOne {
	srdo.srd.mutation.Where(ps...)
	return srdo
}

// Exec executes the deletion query.
func (srdo *StreamRequestDeleteOne) Exec(ctx context.Context) error {
	n, err := srdo.srd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{streamrequest.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (srdo *StreamRequestDeleteOne) ExecX(ctx context.Context) {
	if err := srdo.Exec(ctx); err != nil {
		panic(err)
	}
}
