// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// StreamRequest is the predicate function for streamrequest builders.
type StreamRequest func(*sql.Selector)
